"""
OCIO GPU Shader

Builds GPU display shaders using OpenColorIO.

Responsibilities:
    * Create GPU display transforms.
    * Generate GLSL shader code.
    * Compile OpenGL shaders.
    * Rebuild shaders when OCIO settings change.

Architecture:

    Image Texture
          │
          ▼
    OCIO GPU Shader
          │
          ▼
      OpenGL Screen

Notes:
    This class performs no image processing on the CPU.
    All color conversion occurs on the GPU.
"""

import PyOpenColorIO

from PyOpenColorIO import Config
from PyOpenColorIO import GPUProcessor
from PyOpenColorIO import GpuShaderDesc
from PyOpenColorIO import GpuLanguage

from .gl_shader import GLShader

VERTEX_SHADER = """
#version 330 core

layout(location = 0) in vec2 position;
layout(location = 1) in vec2 texcoord;

out vec2 uv;

void main()
{
    uv = texcoord;
    gl_Position = vec4(position,0.0,1.0);
}
"""


class OCIOShader(object):
    """GPU OCIO display shader."""

    def __init__(self, config_path):
        """
        Initialize OCIO shader.

        Args:
            config_path (str):
                Path to ocio configuration.
        """

        # self.config = Config.CreateFromFile(config_path)
        # self.config = PyOpenColorIO.Config.CreateFromFile(config_path)

        self.processor = None
        self.gpu_processor = None

        self.shader = GLShader()

        self.input_space = None
        self.display = None
        self.view = None

    def _build(self, input_space, display, view):
        """
        Build GPU shader.

        Args:
            input_space (str):
                Image color space.

            display (str):
                Display device.

            view (str):
                Display view.
        """

        self.input_space = input_space
        self.display = display
        self.view = view

        # Build display processor
        processor = self.config.getProcessor(input_space, display, view)

        self.processor = processor

        self.gpu_processor = processor.getDefaultGPUProcessor()

        # Build GLSL shader
        shader_desc = GpuShaderDesc.CreateShaderDesc()

        shader_desc.setLanguage(GpuShaderDesc.LANGUAGE_GLSL_330_CORE)

        shader_desc.setFunctionName("OCIODisplay")

        self.gpu_processor.extractGpuShaderInfo(shader_desc)

        fragment = self.create_fragment_shader(shader_desc.getShaderText())

        self.shader.compile(VERTEX_SHADER, fragment)

    def build(self, ocio_processor):
        """
        Build GPU shader.

        Args:
            input_space (str):
                Image color space.

            display (str):
                Display device.

            view (str):
                Display view.
        """

        # ctransform = ocio_processor.set_display_transform()

        # Build display processor
        # processor = ocio_processor.config.getProcessor(transform)

        self.gpu_processor = ocio_processor.get_default_GPU_processor()

        # Build GLSL shader
        shader_desc = GpuShaderDesc.CreateShaderDesc()

        shader_desc.setLanguage(GpuLanguage.GPU_LANGUAGE_GLSL_4_0)

        shader_desc.setFunctionName("OCIODisplay")

        self.gpu_processor.extractGpuShaderInfo(shader_desc)

        fragment = self.create_fragment_shader(shader_desc.getShaderText())

        self.shader.compile(VERTEX_SHADER, fragment)

    def create_fragment_shader(self, ocio_shader):
        """
        Create complete fragment shader.

        Args:
            ocio_shader (str):
                GLSL code generated by OCIO.

        Returns:
            str

        #version 330 core

        in vec2 uv;

        out vec4 FragColor;

        uniform sampler2D imageTexture;

        {ocio_shader}

        void main()
        {{
            vec4 color = texture(
                imageTexture,
                uv
            );

            color = OCIODisplay(color);

            FragColor = color;
        }}

        """

        codes = [
            "#version 330 core\n",
            "in vec2 uv;\n",
            "out vec4 FragColor;\n",
            "uniform sampler2D imageTexture;\n",
            f"{ocio_shader}\n",
            "void main()\n",
            "{{",
            "\tvec4 color = texture(",
            "\t\timageTexture,",
            "\t\tuv",
            "\t);\n",
            "\tcolor = OCIODisplay(color);\n",
            # "\tcolor.rgb *= vec3(0.0, 1.0, 0.0);",
            "\tFragColor = color;",
            "}}",
        ]

        _codes = [
            "#version 330 core\n",
            "out vec4 FragColor;\n",
            "void main()",
            "{",
            "\tFragColor = vec4(1.0, 0.0, 0.0, 1.0);",
            "}",
        ]

        return "\n".join(codes)

    def bind(self):
        """Bind GPU shader."""

        self.shader.bind()

    def release(self):
        """Release GPU shader."""

        self.shader.release()

    def destroy(self):
        """Destroy OpenGL shader."""

        self.shader.destroy()

    def uniform_location(self, name):
        """Return uniform location."""

        return self.shader.uniform_location(name)

    def set_uniform_int(self, name, value):
        """Set integer uniform."""

        self.shader.set_uniform_int(name, value)

    def set_uniform_float(self, name, value):
        """Set float uniform."""

        self.shader.set_uniform_float(name, value)

    def set_uniform_vec2(self, name, x, y):
        """Set vec2 uniform."""

        self.shader.set_uniform_vec2(name, x, y)

    def set_uniform_vec3(self, name, x, y, z):
        """Set vec3 uniform."""

        self.shader.set_uniform_vec3(name, x, y, z)

    def set_uniform_vec4(self, name, value):
        """Set vec4 uniform."""

        self.shader.set_uniform_vec4(name, value)

    def set_uniform_mat4(self, name, matrix):
        """Set mat4 uniform."""

        self.shader.set_uniform_mat4(name, matrix)


if __name__ == "__main__":
    pass
