"""
OCIO GPU Shader

Builds GPU display shaders using OpenColorIO.

Responsibilities:
    * Create GPU display transforms.
    * Generate GLSL shader code.
    * Compile OpenGL shaders.
    * Rebuild shaders when OCIO settings change.

Architecture:

    Image Texture
          │
          ▼
    OCIO GPU Shader
          │
          ▼
      OpenGL Screen

Notes:
    This class performs no image processing on the CPU.
    All color conversion occurs on the GPU.
"""

from PyOpenColorIO import Config
from PyOpenColorIO import GPUProcessor
from PyOpenColorIO import GPUShaderDesc

from .gl_shader import GLShader


VERTEX_SHADER = """
#version 330 core

layout(location = 0) in vec2 position;
layout(location = 1) in vec2 texcoord;

out vec2 uv;

void main()
{
    uv = texcoord;
    gl_Position = vec4(position,0.0,1.0);
}
"""


class OCIOShader(object):
    """GPU OCIO display shader."""

    def __init__(self, config_path):
        """
        Initialize OCIO shader.

        Args:
            config_path (str):
                Path to ocio configuration.
        """

        self.config = Config.CreateFromFile(config_path)

        self.processor = None
        self.gpu_processor = None

        self.shader = GLShader()

        self.input_space = None
        self.display = None
        self.view = None

    def build(self, input_space, display, view):
        """
        Build GPU shader.

        Args:
            input_space (str):
                Image color space.

            display (str):
                Display device.

            view (str):
                Display view.
        """

        self.input_space = input_space
        self.display = display
        self.view = view

        # Build display processor
        processor = self.config.getProcessor(input_space, display, view)

        self.processor = processor

        self.gpu_processor = processor.getDefaultGPUProcessor()

        # Build GLSL shader
        shader_desc = GPUShaderDesc.CreateShaderDesc()

        shader_desc.setLanguage(GPUShaderDesc.LANGUAGE_GLSL_330_CORE)

        shader_desc.setFunctionName("OCIODisplay")

        self.gpu_processor.extractGpuShaderInfo(shader_desc)

        fragment = self.create_fragment_shader(shader_desc.getShaderText())

        self.shader.compile(VERTEX_SHADER, fragment)

    def create_fragment_shader(self, ocio_shader):
        """
        Create complete fragment shader.

        Args:
            ocio_shader (str):
                GLSL code generated by OCIO.

        Returns:
            str

        #version 330 core

        in vec2 uv;

        out vec4 FragColor;

        uniform sampler2D imageTexture;

        {ocio_shader}

        void main()
        {{
            vec4 color = texture(
                imageTexture,
                uv
            );

            color = OCIODisplay(color);

            FragColor = color;
        }}
                    
        """

        codes = [
            "#version 330 core\n",
            "in vec2 uv;\n",
            "out vec4 FragColor;\n",
            "uniform sampler2D imageTexture;\n",
            f"{ocio_shader}\n",
            "void main()\n",
            "{{",
            "\tvec4 color = texture(",
            "\t\timageTexture,",
            "\t\tuv",
            "\t);\n",
            "\tcolor = OCIODisplay(color);\n",
            "\tFragColor = color;",
            "}}",
        ]

        return "\n".join(codes)

    def bind(self):
        """Bind GPU shader."""

        self.shader.bind()

    def release(self):
        """Release GPU shader."""

        self.shader.release()

    def destroy(self):
        """Destroy OpenGL shader."""

        self.shader.destroy()


if __name__ == "__main__":
    pass